import { useState, useRef, useCallback } from "react";
import axios from "axios";
import "./index.css";

const API_URL = import.meta.env.VITE_API_URL;

// Helpers
function formatBytes(bytes) {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + " " + sizes[i];
}

function getFileIcon(type) {
  if (!type) return "📄";
  if (type.startsWith("image/")) return "🖼️";
  if (type.startsWith("video/")) return "🎬";
  if (type.startsWith("audio/")) return "🎵";
  if (type.includes("pdf")) return "📕";
  if (type.includes("zip") || type.includes("compressed")) return "🗜️";
  if (type.includes("word") || type.includes("document")) return "📝";
  if (type.includes("sheet") || type.includes("excel")) return "📊";
  if (type.includes("json") || type.includes("javascript") || type.includes("text")) return "📋";
  return "📄";
}

function StatusBadge({ status }) {
  const map = {
    idle: { label: "Ready", cls: "badge-idle" },
    uploading: { label: "Uploading…", cls: "badge-uploading" },
    success: { label: "Done", cls: "badge-success" },
    error: { label: "Failed", cls: "badge-error" },
  };
  const { label, cls } = map[status] || map.idle;
  return <span className={`badge ${cls}`}>{label}</span>;
}

export default function App() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [status, setStatus] = useState("idle"); // idle | uploading | success | error
  const [progress, setProgress] = useState(0);
  const [errorMsg, setErrorMsg] = useState("");
  const [history, setHistory] = useState([]);
  const [dragging, setDragging] = useState(false);
  const inputRef = useRef(null);

  const handleFile = (f) => {
    if (!f) return;
    setFile(f);
    setStatus("idle");
    setProgress(0);
    setErrorMsg("");
    if (f.type.startsWith("image/")) {
      const reader = new FileReader();
      reader.onload = (e) => setPreview(e.target.result);
      reader.readAsDataURL(f);
    } else {
      setPreview(null);
    }
  };

  const onDrop = useCallback((e) => {
    e.preventDefault();
    setDragging(false);
    const dropped = e.dataTransfer.files[0];
    if (dropped) handleFile(dropped);
  }, []);

  const onDragOver = (e) => { e.preventDefault(); setDragging(true); };
  const onDragLeave = () => setDragging(false);

  const uploadFile = async () => {
    if (!file) {
      setErrorMsg("Please select a file first.");
      return;
    }

    setStatus("uploading");
    setProgress(0);
    setErrorMsg("");

    try {
      // Step 1: Get pre-signed URL from Lambda
      const res = await axios.get(`${API_URL}?name=${encodeURIComponent(file.name)}`);
      const { uploadUrl } = res.data;

      // Step 2: Upload directly to S3
      await axios.put(uploadUrl, file, {
        headers: { "Content-Type": file.type || "application/octet-stream" },
        onUploadProgress: (e) => {
          const pct = Math.round((e.loaded * 100) / e.total);
          setProgress(pct);
        },
      });

      const fileUrl = uploadUrl.split("?")[0];
      setStatus("success");
      setProgress(100);
      setHistory((prev) => [
        {
          id: Date.now(),
          name: file.name,
          size: file.size,
          type: file.type,
          url: fileUrl,
          uploadedAt: new Date().toLocaleTimeString(),
        },
        ...prev,
      ]);
    } catch (err) {
      console.error(err);
      setStatus("error");
      setErrorMsg(
        err.response?.data?.message ||
        err.message ||
        "Upload failed. Check your API URL in .env"
      );
    }
  };

  const clearFile = () => {
    setFile(null);
    setPreview(null);
    setStatus("idle");
    setProgress(0);
    setErrorMsg("");
    if (inputRef.current) inputRef.current.value = "";
  };

  return (
    <div className="app">
      {/* Header */}
      <header className="header">
        <div className="header-inner">
          <div className="logo">
            <div className="logo-icon">⬆</div>
            <span className="logo-text">SmartUpload</span>
          </div>
          <div className="header-tagline">Serverless • Secure • Instant</div>
        </div>
      </header>

      <main className="main">
        {/* Hero section */}
        <section className="hero">
          <h1 className="hero-title">
            Upload Files to{" "}
            <span className="gradient-text">S3 Instantly</span>
          </h1>
          <p className="hero-sub">
            Pre-signed URLs generated by AWS Lambda. Your files go straight to S3 — no middleman server.
          </p>
        </section>

        {/* Upload Card */}
        <div className="card glass">
          {/* Drop Zone */}
          <div
            className={`drop-zone ${dragging ? "drop-zone--active" : ""} ${file ? "drop-zone--has-file" : ""}`}
            onClick={() => inputRef.current.click()}
            onDrop={onDrop}
            onDragOver={onDragOver}
            onDragLeave={onDragLeave}
          >
            <input
              ref={inputRef}
              id="file-input"
              type="file"
              style={{ display: "none" }}
              onChange={(e) => handleFile(e.target.files[0])}
            />

            {!file ? (
              <div className="drop-zone-empty">
                <div className="drop-icon">☁️</div>
                <p className="drop-label">Drag & drop your file here</p>
                <p className="drop-hint">or click to browse</p>
              </div>
            ) : (
              <div className="file-preview-row" onClick={(e) => e.stopPropagation()}>
                {preview ? (
                  <img src={preview} alt="preview" className="img-thumb" />
                ) : (
                  <div className="file-icon-big">{getFileIcon(file.type)}</div>
                )}
                <div className="file-meta">
                  <span className="file-name">{file.name}</span>
                  <span className="file-size">{formatBytes(file.size)}</span>
                </div>
                <button className="btn-clear" onClick={clearFile} title="Remove file">✕</button>
              </div>
            )}
          </div>

          {/* Progress */}
          {status === "uploading" && (
            <div className="progress-wrap">
              <div className="progress-bar">
                <div className="progress-fill" style={{ width: `${progress}%` }} />
              </div>
              <span className="progress-pct">{progress}%</span>
            </div>
          )}

          {/* Error */}
          {errorMsg && (
            <div className="alert alert-error">
              <span>⚠️</span> {errorMsg}
            </div>
          )}

          {/* Success URL */}
          {status === "success" && history.length > 0 && (
            <div className="alert alert-success">
              <span>✅</span> File uploaded!&nbsp;
              <a href={history[0].url} target="_blank" rel="noopener noreferrer" className="file-url-link">
                View on S3 →
              </a>
            </div>
          )}

          {/* Action button */}
          <button
            id="upload-btn"
            className={`btn-upload ${status === "uploading" ? "btn-upload--loading" : ""}`}
            onClick={uploadFile}
            disabled={status === "uploading"}
          >
            {status === "uploading" ? (
              <>
                <span className="spinner" /> Uploading…
              </>
            ) : (
              "🚀 Upload to S3"
            )}
          </button>

          {/* Status badge */}
          <div className="status-row">
            <StatusBadge status={status} />
            {file && status === "idle" && (
              <span className="status-hint">Ready to upload</span>
            )}
          </div>
        </div>

        {/* How it works */}
        <div className="steps-row">
          {[
            { n: "1", icon: "🔗", label: "Get URL", desc: "Lambda generates a secure pre-signed URL" },
            { n: "2", icon: "📤", label: "Upload", desc: "File goes directly from browser to S3" },
            { n: "3", icon: "🌐", label: "Access", desc: "Receive a public-shareable file URL" },
          ].map((s) => (
            <div key={s.n} className="step-card glass">
              <div className="step-num">{s.n}</div>
              <div className="step-icon">{s.icon}</div>
              <div className="step-label">{s.label}</div>
              <div className="step-desc">{s.desc}</div>
            </div>
          ))}
        </div>

        {/* Upload History */}
        {history.length > 0 && (
          <section className="history-section">
            <h2 className="history-title">
              📂 Upload History <span className="history-count">{history.length}</span>
            </h2>
            <div className="history-list">
              {history.map((item) => (
                <div key={item.id} className="history-item glass">
                  <div className="history-icon">{getFileIcon(item.type)}</div>
                  <div className="history-meta">
                    <span className="history-name">{item.name}</span>
                    <span className="history-info">{formatBytes(item.size)} · {item.uploadedAt}</span>
                  </div>
                  <a href={item.url} target="_blank" rel="noopener noreferrer" className="history-link">
                    Open ↗
                  </a>
                </div>
              ))}
            </div>
          </section>
        )}
      </main>

      <footer className="footer">
        Built with <span className="heart">♥</span> using React · AWS Lambda · S3
      </footer>
    </div>
  );
}
